### ISSUE TITLE
AWS secret key and access key exposed

### ISSUE THREAD

**Issue by abhitnc** [saadgen/cloud_agnostic_cicd_k8#1]
AWS secret key and access key exposed.

[https://github.com/saadgen/cloud_agnostic_cicd_k8/blob/1b892c9ac972517f2b04c5c59276b37f9b9ceda0/aws/ansible-executor/backup/terraform-jenkins-code/terraform.tfvars](https://github.com/saadgen/cloud_agnostic_cicd_k8/blob/1b892c9ac972517f2b04c5c59276b37f9b9ceda0/aws/ansible-executor/backup/terraform-jenkins-code/terraform.tfvars)

**Comment by saadgen** [comment]
Fixed

**Comment by saadgen** [comment]
this token is just to make fool
